onerandomusername/monty-python

monty/exts/info/docs/_html.py
monty/statsd.py
monty/utils/__init__.py
monty/utils/converters.py
monty/utils/extensions.py
monty/utils/function.py
monty/utils/helpers.py
monty/utils/html_parsing.py
monty/utils/lock.py
monty/utils/markdown.py
monty/utils/pagination.py
monty/utils/scheduling.py
pyproject.toml

Fixes a couple typing issues, mainly in `monty.utils`, lowering the error count by about 50.
Entirely untested as I currently don't have a proper environment with pg and redis set up, but they're largely non-runtime changes anyway.

typing: fix typing issues in utils

---

monty/exts/api/realpython.py
monty/exts/api/stackoverflow.py
monty/exts/api/wikipedia.py
monty/exts/backend/bot_features.py
monty/exts/backend/rollouts.py
monty/exts/filters/token_remover.py
monty/exts/filters/webhook_remover.py
monty/exts/info/codeblock_commands.py
monty/exts/info/codesnippets.py
monty/exts/info/docs/_cog.py
monty/exts/info/github_info.py
monty/exts/info/global_source.py
monty/exts/info/pep.py
monty/exts/info/source.py
monty/exts/utils/status_codes.py
monty/exts/utils/timed.py

This uses the `name` kwarg for `Cog` subclasses. Reason being that they look quite weird on the help command.
NOTE: Has not been tested ~~because I have no idea how this bot works :^)~~

refactor(exts): add spaced out names to cogs

---

monty/exts/info/discord.py

The button that should show up for `/discord app-invite` was inadvertently replaced by the delete button in 6900fcacc0f04bdb970154e4bb75ac62e1523e26, this fixes the component logic.
untested.

fix: restore `/discord app-invite` button

---

monty/exts/info/meta.py

There's a lot of meta commands, and some of them are duplicates. This tries to consolidate them a bit in order to cut down on the `/monty` spam.

feat: reword/expand meta commands

---

monty/exts/info/github_info.py

by default we now show this instead of the discord embed for issues.
todo: 
- configuration option
- edit: made this a feature lock for the time being
- more testing of behavior when a message is edited
- testing of when multiple links are provided

feat: expand GitHub issue links

---

monty/exts/info/github_info.py

Rather than matching `https://github.com/onerandomusername/monty-python/pull/231/commits/` we only want to match `https://github.com/onerandomusername/monty-python/pull/231/` or `https://github.com/onerandomusername/monty-python/pull/231` (outside of codeblocks)

fix(gh-issues): only match exact issue urls

---

monty/constants.py
monty/exts/info/github_info.py
monty/utils/markdown.py

Improves the previews for GitHub issues. This should be the last blocker before rolling out expanded descriptions across the entire bot.
https://github.com/DisnakeDev/disnake/pull/986
https://github.com/starlite-api/starlite/pull/1317

feat: better markdown previews for GitHub issues

---

monty/exts/info/github_info.py

When a GitHub link is parenthetically wrapped, it causes the regex match to fail.
Example:
```
Yeah that is fixed (See: https://github.com/issues/1)
```
Would fail because the ending issue ID is touching a paren..
This resolves that.

fix: ignore parenthesis on GitHub issue expansion regex matching

---

monty/constants.py
monty/exts/info/python_discourse.py

Adds an autolinker for https://discuss.python.org.
Pretty basic, only links topics and posts. The regex for url detection is not complete, as Discourse allows a plethora of ways to link to a post or topic.
todo:
- add a configuration option and generate migrations
later todo:
- add a dropdown configuration for all autolinkers

feat: add python discourse autolinking

---

monty/exts/info/codesnippets.py

Introduces a fixed mapping for specific file extensions to different languages, only entry for now being `.pyi` -> `py` (I can't think of any others right now).
Previously, `.pyi` files wouldn't be highlighted, since hl.js doesn't recognize the `pyi` language:
As per PEP 484, .py and .pyi files have the same syntax.

feat: map .pyi to py language in codesnippets

---

monty/exts/info/github_info.py

Seems like these are now being rendered on the latest canary build:
... I don't think there's a reason to escape them there(?)

fix: don't escape parentheses in github embed

---

monty/utils/messages.py

Increases the max wait time for `utils.messages.suppress_embeds` from 3s to 6s; there have been a few rare cases where Discord took longer than those 3 seconds to generate an embed, so it didn't get suppressed by the bot.
ref: https://canary.discord.com/channels/755868545279328417/1097569981761339473

fix: increase suppress_embeds wait time to 6s

---

monty/utils/html_parsing.py

Prevents this from showing up after recent markdown parsing changes on Discord's end:
Previously, all `¶` symbols would simply be removed, leaving an empty link name. Since empty link names are no longer permitted by Discord's markdown parser, these links are no longer hidden.
This PR removes the header links from the page hierarchy entirely, instead of relying on string operations for just that symbol alone.
ref: https://canary.discord.com/channels/755868545279328417/1099689844789227551

fix: completely remove `.headerlink` from documentation markup

---

.github/dependabot.yaml

This reverts commit 13c5ec5e8d5ce9796dab34dfd9cf4e908ccb473c.

Revert "chore: disable dependabot for pip"

---

monty/__init__.py

Paginators are currently broken, see https://canary.discord.com/channels/755868545279328417/952320005251411978/1286694032529031279
```py
Traceback (most recent call last):
File "/workspaces/monty-python/.venv/lib/python3.11/site-packages/disnake/ext/commands/core.py", line 173, in wrapped
ret = await coro(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/workspaces/monty-python/monty/exts/info/utils.py", line 98, in snowflake
await LinePaginator.paginate(lines, ctx=ctx, embed=embed, max_lines=5, max_size=1000)
File "/workspaces/monty-python/monty/utils/pagination.py", line 184, in paginate
log.trace(f"Added line to paginator: '{line}'")
^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'trace'
```
This was caused by the fact that `monkey_patches` now imports `monty.utils`, …

fix: set up logging before importing other modules

---

.github/workflows/lint_test_build.yaml
.github/workflows/status_embed.yaml

This removes the workflow steps for sending an embed through a Discord webhook for PR checks, because god is it spammy. i think dependabot is slowly making me lose my sanity.
Workflow events/checks from branches in the repo are still sent to the webhook; this just removes the PR part.
disclaimer, untested c:

ci: don't send discord embed on PR workflow event

---

.github/workflows/status_embed.yaml

apparently double quotes aren't valid here, while single quotes [are](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idif)
i love yaml
followup to #311

fix(ci): make status embed workflow run again

---

monty/utils/markdown.py

The old regex didn't account for all valid cases:
- a reference may be preceded by any non-word character (or line start), not just whitespace
- it should have a word boundary at the end
- a lowercase `gh-` is also valid
| old regex | new regex |
|:------:|:------:|
| ![image](https://github.com/user-attachments/assets/1c15dd47-2c66-4aa0-acff-0bb09e389a19) | ![image](https://github.com/user-attachments/assets/dd5f1f21-5648-46c9-9ead-c5c7752b6a1c) | 
Note that these only work as shown with a fix that's part of #333, which fixes displaying links in lists.
There are a couple other valid issue reference formats as evident in those screenshots, which I might implement some other time.

fix(markdown): improve handling of github issue references

---

monty/utils/markdown.py

Several improvements/fixes to the markdown renderer:
- simplify codeblock detection in lists, also preventing some weird edge cases (previously #244)
- avoid double-rendering text in lists, related to #331
- render lists into proper list markdown, now that Discord supports it. no more `\u2001` and `\u2007` weirdness
- fix heading levels being rendered the wrong way around (e.g. `# abc` was being turned into `### abc`, and vice versa)

fix: markdown stuff

---

monty/bot.py

With `DeprecationWarning`s turned on, prints a warning after the update in #306 when the bot stops:
```py
/workspaces/monty-python/monty/bot.py:381: DeprecationWarning: Call to deprecated close. (Use aclose() instead) -- Deprecated since version 5.0.1.
await self.redis_session.close(close_connection_pool=True)
```

fix: use `redis.aclose()`

---

monty/exts/info/github_info.py
monty/utils/services.py

This removes the resource name from the model (since it's already present in the dict key), and groups the command output into 3 columns instead of 1, resulting in a much more readable output. Also works fine on mobile.
| looooooong embed | not so long embed |
|:------:|:------:|
| ![image](https://github.com/user-attachments/assets/33fc9242-0975-471a-b81d-b1342272dbd6) | ![image](https://github.com/user-attachments/assets/300f79a6-73a8-40d5-96eb-bea0150fe642) |

feat: slightly adjust ratelimit command output

---

monty/bot.py
monty/exts/backend/error_handler.py
monty/exts/info/docs/_cog.py
monty/exts/info/github_info.py
monty/exts/info/pypi.py
monty/utils/caching.py
pyproject.toml

`logging.Logger.warn` has been deprecated since Python 3.3.

lint: enable `flake8-logging-format` ruff ruleset

---

monty/exts/info/github_info.py

These links didn't work at all before (or maybe they did at some point, and GitHub changed their API? kind of doubt that, though), there's a separate endpoint for fetching reviews as opposed to review *comments*.
Example link: https://github.com/onerandomusername/monty-python/pull/343#pullrequestreview-2335885396

fix(github): fix `#pullrequestreview-` links

---

monty/exts/info/github_info.py

as commonly requested not only by me, but also others.
The logic for *expanding* is the same as before, only the original author can publicly expand the embed; anyone else (including moderators) gets an ephemeral embed.
This just allows moderators (generally anyone with `manage_messages`) to *collapse* these embeds.

feat(github): allow moderators to collapse embeds

---

monty/utils/html_parsing.py

`Tag`s are also `PageElement`s, so this check skipped the element it's looking for.

fix(docs): fix symbol markdown parser
